// Automatically generated by astro-icon
// 89bb8a005e70419a5c7b5f914f5ceea2fbb2b8624e44471c377f074ec5fab9fb

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "auto"
		| "bulb"
		| "bullseye"
		| "case"
		| "check"
		| "cloud"
		| "compass"
		| "cpu"
		| "cross"
		| "dirt"
		| "doller"
		| "euro"
		| "graph"
		| "help"
		| "history"
		| "location"
		| "location_pin"
		| "mail"
		| "minus"
		| "monitor"
		| "phone"
		| "profile"
		| "right"
		| "rocket"
		| "speed"
		| "task"
		| "tick"
		| "time"
		| "up"
		| "upward";
}