import type { APIContext } from "astro";
import { client, queries } from "@/lib/sanity";

export const prerender = false;

export async function GET(context: APIContext) {
  const site = context.site?.toString().replace(/\/$/, "") || "https://kowalah.com";

  const urls: Array<{
    loc: string;
    lastmod?: string;
    changefreq: string;
    priority: number;
  }> = [];

  // Static SSR pages (not generated by @astrojs/sitemap because prerender = false)
  urls.push(
    { loc: `${site}/insights`, changefreq: "daily", priority: 0.9 },
    { loc: `${site}/categories`, changefreq: "weekly", priority: 0.5 },
    { loc: `${site}/customers`, changefreq: "monthly", priority: 0.6 },
    { loc: `${site}/customers/share-story`, changefreq: "monthly", priority: 0.4 },
    { loc: `${site}/resources/wednesday-webinars`, changefreq: "weekly", priority: 0.7 },
  );

  // Blog posts from Sanity
  try {
    const posts = await client.fetch(`
      *[_type == "post" && defined(publishedAt) && publishedAt <= now() && !(_id in path("drafts.**"))] | order(publishedAt desc) {
        "slug": slug.current,
        publishedAt,
        _updatedAt
      }
    `);

    for (const post of posts) {
      if (post.slug) {
        urls.push({
          loc: `${site}/insights/${post.slug}`,
          lastmod: post._updatedAt || post.publishedAt,
          changefreq: "monthly",
          priority: 0.8,
        });
      }
    }
  } catch (error) {
    console.error("Sitemap: Failed to fetch posts from Sanity", error);
  }

  // Category pages from Sanity (only categories with published posts)
  try {
    const categories = await client.fetch(`
      *[_type == "category" && count(*[_type == "post" && defined(publishedAt) && publishedAt <= now() && !(_id in path("drafts.**")) && references(^._id)]) > 0] {
        "slug": slug.current
      }
    `);

    for (const category of categories) {
      if (category.slug) {
        urls.push({
          loc: `${site}/categories/${category.slug}`,
          changefreq: "weekly",
          priority: 0.6,
        });
      }
    }
  } catch (error) {
    console.error("Sitemap: Failed to fetch categories from Sanity", error);
  }

  // Webinars from Sanity
  try {
    const webinars = await client.fetch(`
      *[_type == "webinar" && !(_id in path("drafts.**"))] {
        "slug": slug.current,
        _updatedAt,
        date
      }
    `);

    for (const webinar of webinars) {
      if (webinar.slug) {
        urls.push({
          loc: `${site}/resources/wednesday-webinars/${webinar.slug}`,
          lastmod: webinar._updatedAt || webinar.date,
          changefreq: "monthly",
          priority: 0.6,
        });
      }
    }
  } catch (error) {
    console.error("Sitemap: Failed to fetch webinars from Sanity", error);
  }

  // Generate XML
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (url) => `  <url>
    <loc>${url.loc}</loc>${url.lastmod ? `\n    <lastmod>${new Date(url.lastmod).toISOString().split("T")[0]}</lastmod>` : ""}
    <changefreq>${url.changefreq}</changefreq>
    <priority>${url.priority}</priority>
  </url>`,
  )
  .join("\n")}
</urlset>`;

  return new Response(sitemap, {
    status: 200,
    headers: {
      "Content-Type": "application/xml",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
